import { CommercialCatalogOffer } from "@workspace/db/schema";

// Catálogo privado, curado para venta consultiva. Los importes son rangos de
// implantación orientativos, no garantías de facturación ni precios publicados.
const CATALOG = [
  {
    slug: "obra-eficiente-360",
    title: "Obra Eficiente 360",
    vertical: "Rehabilitación energética y construcción",
    deliveryModel: "Plataforma B2B de expedientes y ejecución de obra",
    summary: "Coordina expediente energético, documentación de ayudas, presupuesto, avance de obra y justificación para rehabilitadoras, administradores y técnicos.",
    buyer: "Pymes de rehabilitación, arquitectos técnicos, administradores de fincas y oficinas de rehabilitación.",
    differentiator: "No sustituye el software de mediciones: conecta elegibilidad energética, evidencias de obra y trazabilidad documental en un único expediente.",
    modules: ["Expedientes por edificio", "Checklist de ayudas", "Timeline de obra", "Solicitudes a proveedores", "Portal de comunidad", "Cuadro de evidencias"],
    integrations: ["Certificación energética", "Firma electrónica", "Almacenamiento documental", "ERP de obra"],
    pricing: { implementationMinEur: 35000, implementationMaxEur: 125000, enterpriseProgramMaxEur: 350000, recurringFromEur: 750 },
    regulatoryNotes: "La plataforma organiza evidencias y flujos; la elegibilidad de subvenciones, dirección facultativa y certificaciones siguen siendo responsabilidad de profesionales habilitados.",
    researchSources: ["https://www.mivau.gob.es/vivienda/rehabilitacion", "https://www.boe.es/buscar/doc.php?id=BOE-A-2021-16230"],
  },
  {
    slug: "carelink-familias",
    title: "CareLink Familias",
    vertical: "Cuidados domiciliarios y economía plateada",
    deliveryModel: "Plataforma B2B2C de coordinación de cuidados",
    summary: "Organiza visitas, tareas, incidencias, autorizaciones y comunicación entre familiares, cuidador, SAD, farmacia y profesionales autorizados.",
    buyer: "Empresas de atención domiciliaria, aseguradoras asistenciales, cooperativas de cuidados y ayuntamientos.",
    differentiator: "Capa neutral de coordinación longitudinal para varios intervinientes, sin intentar sustituir la historia clínica ni el criterio profesional.",
    modules: ["Plan de cuidados", "Agenda de visitas", "Portal familiar", "Alertas de tareas", "Consentimientos", "Derivación humana"],
    integrations: ["Calendario", "Teleasistencia", "Firma", "CRM asistencial"],
    pricing: { implementationMinEur: 50000, implementationMaxEur: 180000, enterpriseProgramMaxEur: 500000, recurringFromEur: 1200 },
    regulatoryNotes: "Debe aplicar RGPD y separar información sanitaria. No realiza diagnóstico ni recomendaciones clínicas autónomas.",
    researchSources: ["https://www.ine.es", "https://imserso.es"],
  },
  {
    slug: "comunidad-clara",
    title: "Comunidad Clara",
    vertical: "Comunidades de propietarios",
    deliveryModel: "Capa de transparencia e incidencias para administradores de fincas",
    summary: "Convierte obras, incidencias, cuotas, acuerdos y documentación comunitaria en expedientes explicables para vecinos y proveedores.",
    buyer: "Despachos de administración de fincas y grupos de comunidades.",
    differentiator: "Se integra sobre el ERP existente y reduce fricción con trazabilidad, lenguaje claro y resolución guiada de expedientes.",
    modules: ["Expedientes de incidencias", "Portal vecinal", "Seguimiento de obras", "Acuerdos y actas", "Proveedores", "Centro de documentos"],
    integrations: ["Fynkus/Gesfincas mediante API", "Firma", "Correo", "Banca para lectura autorizada"],
    pricing: { implementationMinEur: 30000, implementationMaxEur: 110000, enterpriseProgramMaxEur: 280000, recurringFromEur: 650 },
    regulatoryNotes: "La gestión de datos de propietarios exige roles, trazabilidad y mínimos privilegios. No sustituye asesoramiento jurídico ni administración colegiada.",
    researchSources: ["https://www.cgcafe.org", "https://www.ocu.org"],
  },
  {
    slug: "circular-garage",
    title: "Circular Garage",
    vertical: "Talleres, recambios y economía circular",
    deliveryModel: "SaaS B2B para reparación circular",
    summary: "Mide reparabilidad, reutilización, recambio recuperado y destino de residuos por orden de taller, vehículo y proveedor.",
    buyer: "Redes de talleres, CAT, aseguradoras de reparación y distribuidores de recambio.",
    differentiator: "Añade trazabilidad circular y propuesta económica verificable sobre el DMS del taller, no otro sistema de órdenes genérico.",
    modules: ["Orden circular", "Catálogo de recambio recuperado", "Evidencias de desmontaje", "Huella por reparación", "Portal aseguradora", "Informes ESG"],
    integrations: ["DMS", "Catálogos de piezas", "ERP", "Firma de recepción"],
    pricing: { implementationMinEur: 45000, implementationMaxEur: 160000, enterpriseProgramMaxEur: 450000, recurringFromEur: 1000 },
    regulatoryNotes: "La trazabilidad de residuos y actividad CAT requiere validar el flujo concreto con gestores autorizados y normativa aplicable.",
    researchSources: ["https://www.boe.es/buscar/doc.php?id=BOE-A-2021-13214", "https://www.dgt.es"],
  },
  {
    slug: "nexo-animal",
    title: "Nexo Animal",
    vertical: "Veterinaria, protectoras y bienestar animal",
    deliveryModel: "Plataforma B2B2C de continuidad asistencial y adopción",
    summary: "Conecta clínica, tutor, protectora y administración para seguimiento, prevención de abandono, adopción responsable e informes de bienestar.",
    buyer: "Redes veterinarias, protectoras, municipios y fundaciones de bienestar animal.",
    differentiator: "No reemplaza el ERP clínico: coordina el ciclo identificación–tratamiento–acogida–adopción con permisos y objetivos compartidos.",
    modules: ["Ficha de seguimiento", "Portal de tutor", "Expediente de acogida", "Protocolos de adopción", "Alertas de vacunas", "Panel municipal"],
    integrations: ["ERP veterinario", "Microchip/registro autorizado", "Pasarela de pagos", "Firma"],
    pricing: { implementationMinEur: 55000, implementationMaxEur: 200000, enterpriseProgramMaxEur: 550000, recurringFromEur: 1500 },
    regulatoryNotes: "Requiere contratos de tratamiento de datos y validación de cualquier integración con registros autonómicos o colegiales.",
    researchSources: ["https://www.boe.es/buscar/act.php?id=BOE-A-2023-7936", "https://www.veterindustria.com"],
  },
  {
    slug: "origen-directo",
    title: "Origen Directo",
    vertical: "Productores agroalimentarios y canal corto",
    deliveryModel: "Marketplace B2B2C de origen verificable",
    summary: "Gestiona lotes, previsión de cosecha, pedidos compartidos, trazabilidad, rutas locales y venta directa para pequeños productores.",
    buyer: "Cooperativas, agrupaciones de productores, mercados de origen y distribuidores de proximidad.",
    differentiator: "Conecta trazabilidad operativa y venta multicanal con previsión de oferta; no es una tienda genérica ni un simple marketplace de alimentos.",
    modules: ["Lotes y origen", "Previsión de cosecha", "Pedidos agrupados", "Rutas locales", "Portal comprador", "Etiquetas QR"],
    integrations: ["TPV", "Logística", "Facturación", "Etiquetado"],
    pricing: { implementationMinEur: 40000, implementationMaxEur: 150000, enterpriseProgramMaxEur: 420000, recurringFromEur: 900 },
    regulatoryNotes: "La información alimentaria, trazabilidad y etiquetado debe validarse con el operador alimentario responsable.",
    researchSources: ["https://www.mapa.gob.es", "https://observatorioagroalimentario.gob.es"],
  },
  {
    slug: "ruta-accesible-rural",
    title: "Ruta Accesible Rural",
    vertical: "Turismo rural y accesibilidad",
    deliveryModel: "Plataforma de reservas directas y experiencias verificadas",
    summary: "Combina disponibilidad rural, necesidades de accesibilidad, experiencias locales y comunicación previa con el anfitrión.",
    buyer: "Redes de alojamientos rurales, mancomunidades, agencias de destino y grupos de desarrollo rural.",
    differentiator: "La ficha no solo declara accesibilidad: organiza evidencias, necesidades del visitante, respuesta operativa y paquete de experiencia local.",
    modules: ["Motor de disponibilidad", "Perfil de accesibilidad", "Experiencias", "Solicitud asistida", "CRM de destino", "Analítica de conversión"],
    integrations: ["PMS", "Calendario", "Pasarela de pagos", "Oficinas de turismo"],
    pricing: { implementationMinEur: 35000, implementationMaxEur: 130000, enterpriseProgramMaxEur: 300000, recurringFromEur: 800 },
    regulatoryNotes: "No debe declarar accesibilidad no comprobada; las condiciones de reserva y seguros dependen de cada operador.",
    researchSources: ["https://www.ine.es", "https://www.segittur.es"],
  },
  {
    slug: "planta-lista",
    title: "Planta Lista",
    vertical: "Pymes industriales y servicio técnico",
    deliveryModel: "Plataforma B2B de mantenimiento ejecutable",
    summary: "Transforma señales, partes y alertas en una orden ejecutable con técnico, repuesto, ventana de parada y aprendizaje de incidencias.",
    buyer: "Fabricantes, mantenedores industriales, empresas de maquinaria y distribuidores de repuestos.",
    differentiator: "Resuelve el último kilómetro: alertas que terminan en intervención trazable, no un cuadro de mando IoT aislado.",
    modules: ["Registro de activos", "Órdenes de trabajo", "Matriz de repuestos", "Planificador de técnicos", "Portal cliente", "Base de conocimiento"],
    integrations: ["ERP", "IoT/SCADA", "CMMS", "Catálogo de repuestos"],
    pricing: { implementationMinEur: 75000, implementationMaxEur: 250000, enterpriseProgramMaxEur: 800000, recurringFromEur: 2000 },
    regulatoryNotes: "La plataforma no sustituye procedimientos de seguridad industrial, mantenimiento normativo ni decisiones de ingeniería.",
    researchSources: ["https://www.mincotur.gob.es", "https://www.eoi.es"],
  },
  {
    slug: "return-local",
    title: "ReTurn Local",
    vertical: "Comercio local y envase reutilizable",
    deliveryModel: "SaaS B2B de venta omnicanal y retorno",
    summary: "Permite a comercios coordinar catálogo, reserva, devolución, depósito, limpieza y reuso de envases por barrio o red de tiendas.",
    buyer: "Asociaciones de comercio, cadenas locales, mercados municipales y operadores de envase reutilizable.",
    differentiator: "Une pedidos, devolución y trazabilidad de envase reutilizable, no solo comercio electrónico ni programa de fidelización.",
    modules: ["Catálogo compartido", "Reserva local", "QR de envase", "Depósito y retorno", "Panel de tienda", "Informe de reuso"],
    integrations: ["TPV", "Pasarela de pagos", "Logística local", "CRM"],
    pricing: { implementationMinEur: 45000, implementationMaxEur: 160000, enterpriseProgramMaxEur: 450000, recurringFromEur: 1100 },
    regulatoryNotes: "El sistema debe adaptar obligaciones de envases, privacidad y reglas de depósitos al modelo operativo de cada red.",
    researchSources: ["https://comercio.gob.es", "https://www.miteco.gob.es"],
  },
  {
    slug: "rcd-loop",
    title: "RCD Loop",
    vertical: "Residuos de construcción y materiales reutilizables",
    deliveryModel: "Marketplace B2B de circularidad de obra",
    summary: "Coordina inventario pre-demolición, separación, certificados, logística y venta local de materiales recuperados entre obras y gestores.",
    buyer: "Constructoras, gestores de RCD, promotores, municipios y plantas de valorización.",
    differentiator: "Conecta demolición selectiva, documentación obligatoria y demanda local de materiales; no solo rutas de residuos o compraventa genérica.",
    modules: ["Inventario de deconstrucción", "Documentos de traslado", "Marketplace de materiales", "Trazabilidad por obra", "Logística", "Panel de certificados"],
    integrations: ["Gestores autorizados", "ERP de obra", "Firma", "GIS"],
    pricing: { implementationMinEur: 85000, implementationMaxEur: 300000, enterpriseProgramMaxEur: 1000000, recurringFromEur: 2500 },
    regulatoryNotes: "Debe operar con gestores y transportistas autorizados; la plataforma no certifica por sí misma el tratamiento de residuos.",
    researchSources: ["https://www.miteco.gob.es", "https://www.boe.es/buscar/doc.php?id=BOE-A-2008-2486"],
  },
  {
    slug: "nexo-club",
    title: "NexoClub",
    vertical: "Clubes deportivos y escuelas extraescolares",
    deliveryModel: "Plataforma B2B2C multi-sede",
    summary: "Centraliza familias, cuotas, becas, asistencia, transporte, voluntariado, comunicación y protección operativa de menores.",
    buyer: "Clubes, academias, escuelas extraescolares, federaciones locales y centros multideporte.",
    differentiator: "Más que inscripciones: resuelve la operación multi-sede, conciliación familiar, voluntariado y consentimiento por actividad.",
    modules: ["Inscripciones", "Cobros", "Asistencia", "Comunicación familiar", "Gestión de voluntariado", "Portal multi-sede"],
    integrations: ["Pagos", "Firma de consentimientos", "Calendario", "Contabilidad"],
    pricing: { implementationMinEur: 25000, implementationMaxEur: 90000, enterpriseProgramMaxEur: 250000, recurringFromEur: 500 },
    regulatoryNotes: "El tratamiento de datos de menores exige especial diligencia, controles de acceso y consentimientos adecuados.",
    researchSources: ["https://www.csd.gob.es", "https://www.ine.es"],
  },
  {
    slug: "barrio-flow",
    title: "BarrioFlow",
    vertical: "Última milla y servicios de proximidad",
    deliveryModel: "Plataforma B2B multioperador de coordinación urbana",
    summary: "Coordina servicios, entregas, franjas, consolidación, retornos y prueba de prestación entre comercio, repartidor, cliente y municipio.",
    buyer: "Operadores de última milla, hubs urbanos, asociaciones comerciales y plataformas de servicios de proximidad.",
    differentiator: "No compite por una sola flota: orquesta varios operadores, carga útil, retorno y ventanas urbanas bajo reglas locales.",
    modules: ["Despacho de servicios", "Ventanas de entrega", "Prueba de prestación", "Consolidación", "Retornos", "Panel municipal"],
    integrations: ["Mapas", "Flotas", "TPV", "Notificaciones"],
    pricing: { implementationMinEur: 100000, implementationMaxEur: 400000, enterpriseProgramMaxEur: 1200000, recurringFromEur: 3500 },
    regulatoryNotes: "La operación debe ajustarse a ordenanzas, licencias, seguro, datos de geolocalización y normativa laboral de cada operador.",
    researchSources: ["https://www.transportes.gob.es", "https://observatoriotransporte.mitma.es"],
  },
] as const;

export async function seedCommercialCatalog(createdByUserId: string) {
  const operations = CATALOG.map((offer) => ({
    updateOne: {
      filter: { slug: offer.slug },
      update: { $setOnInsert: { ...offer, createdByUserId, commercialStatus: "ready_to_generate" } },
      upsert: true,
    },
  }));
  const result = await CommercialCatalogOffer.bulkWrite(operations, { ordered: false });
  return { total: CATALOG.length, inserted: result.upsertedCount || 0, unchanged: CATALOG.length - (result.upsertedCount || 0) };
}

export async function listCommercialCatalog() {
  return CommercialCatalogOffer.find({}).sort({ vertical: 1, title: 1 }).lean();
}
