import { GoogleGenAI, Modality } from "@google/genai";
import { eq } from "drizzle-orm";
import { db } from "./db";
import { appImages, generatedApps } from "@workspace/db/schema";
import { logger } from "./logger";

/* ============================================================================
 * AppForge Image Agent — Nano Banana Pro
 *
 * After the Coder finishes a bundle (or on demand from the UI), this scans
 * for placeholder image URLs (Unsplash / picsum / source.unsplash) and
 * replaces them with real images generated by Gemini 3 Pro Image
 * (`gemini-3-pro-image-preview`, a.k.a. Nano Banana Pro).
 *
 * Cost & latency are real concerns:
 *   - Pro images are slow (~10-15s each)
 *   - Capped at MAX_IMAGES per call
 *   - Run with bounded parallelism (CONCURRENCY)
 *   - Failures of individual images are swallowed — we still patch the URLs
 *     that succeeded and leave the rest as placeholders.
 *
 * Storage: rows in `app_images` keyed by app, served as binary from
 * `/api/apps/:appId/images/:imageId` (public, immutable). We replace the
 * placeholder URL in the bundle with that path so it works in both Sandpack
 * preview AND the public `/p/:slug` deploy.
 * ========================================================================== */

const MAX_IMAGES = 16;
const CONCURRENCY = 3;

/**
 * Build the public absolute base URL of the API server. We need ABSOLUTE URLs
 * for the generated image paths because the Sandpack live preview executes
 * the bundle inside an iframe served from a Sandpack-controlled domain
 * (`*.csb.app`), so a relative `/api/apps/3/images/1` would resolve against
 * the Sandpack origin and 404. The same absolute URL also works fine in the
 * public `/p/<slug>` deploy (same origin).
 */
function appBaseUrl(): string {
  const host = (process.env.REPLIT_DOMAINS ?? "").split(",")[0].trim();
  return host ? `https://${host}` : "";
}

// Use the dedicated client so we can pass the Pro model explicitly. The
// shared `ai` client at @workspace/integrations-gemini-ai uses the same env
// vars; we re-instantiate here only because the helper exported from the lib
// pins the flash image model and we want to opt into Pro per the user's
// request ("nano banana pro el nuevo actual").
const imageClient = new GoogleGenAI({
  apiKey: process.env.AI_INTEGRATIONS_GEMINI_API_KEY,
  httpOptions: {
    apiVersion: "",
    baseUrl: process.env.AI_INTEGRATIONS_GEMINI_BASE_URL,
  },
});

const PLACEHOLDER_URL_REGEX =
  /https?:\/\/(?:images\.unsplash\.com|source\.unsplash\.com|picsum\.photos)\/[^\s"'`)<>]+/g;

interface FoundPlaceholder {
  url: string;
  altText: string;
}

/**
 * Find unique placeholder URLs in a bundle and grab a small bit of context
 * (alt text or nearby JSX text) for prompting. Order is preserved so the
 * "first 4" the model sees match the order they appear in the source.
 */
export function findPlaceholders(bundle: string): FoundPlaceholder[] {
  const found = new Map<string, FoundPlaceholder>();
  const re = new RegExp(PLACEHOLDER_URL_REGEX.source, "g");
  let m: RegExpExecArray | null;
  while ((m = re.exec(bundle)) !== null) {
    const url = m[0];
    if (found.has(url)) continue;
    // Strip trailing punctuation that can't legally be part of a URL inside JSX.
    const cleanUrl = url.replace(/[.,;:!?]+$/g, "");
    if (found.has(cleanUrl)) continue;
    const start = Math.max(0, m.index - 200);
    const end = Math.min(bundle.length, m.index + cleanUrl.length + 80);
    const window_ = bundle.slice(start, end);
    let altText = "";
    const altMatch = /alt\s*=\s*["'`]([^"'`]{2,160})["'`]/.exec(window_);
    if (altMatch) {
      altText = altMatch[1];
    } else {
      // Fall back to the nearest JSX text node before the URL.
      const before = bundle.slice(start, m.index);
      const textMatch = /[>}]\s*([A-Za-zÀ-ÿ0-9 ,.\-]{4,120})\s*[<{]/g;
      let last: RegExpExecArray | null = null;
      let tm: RegExpExecArray | null;
      while ((tm = textMatch.exec(before)) !== null) last = tm;
      if (last) altText = last[1].trim();
    }
    found.set(cleanUrl, { url: cleanUrl, altText: altText.slice(0, 200) });
    if (found.size >= MAX_IMAGES) break;
  }
  return Array.from(found.values());
}

function buildPrompt(altText: string, appTitle: string, appDescription: string): string {
  const subject = altText && altText.length > 3
    ? altText
    : `imagen ilustrativa para "${appTitle}"`;
  // Detect avatar/portrait context so we direct the model toward portrait
  // composition instead of product photography.
  const altLower = altText.toLowerCase();
  const isAvatar = /avatar|usuari|perfil|persona|cara|cliente|vendedor|comprador|review|testimoni/.test(altLower);
  const isHero = /hero|banner|portada|fondo|cover|cabecera/.test(altLower);

  // Nano Banana Pro responds best to concrete, photographic direction. We
  // include subject + context + style + lighting + composition + camera + a
  // strict "no text" guardrail. Square aspect-ratio is requested in the prompt
  // text since this model doesn't expose a separate aspect param.
  let style: string;
  if (isAvatar) {
    style =
      "Retrato fotográfico profesional de una persona real, ángulo frontal, fondo desenfocado neutro, iluminación natural suave tipo ventana, expresión amable y natural, encuadre desde los hombros hacia arriba, foco nítido en los ojos. Estilo editorial moderno tipo The Verge / Apple. Formato cuadrado 1:1. No incluyas ningún texto, logo, marca de agua ni elementos generados artificialmente";
  } else if (isHero) {
    style =
      "Imagen cinematográfica de gran formato, profundidad de campo amplia, iluminación dorada o azulada con dirección clara, composición que respira, paleta de colores limitada y sofisticada. Estilo de portada editorial moderna. Formato cuadrado 1:1. Sin texto, sin logos, sin marcas de agua";
  } else {
    style =
      "Fotografía de producto profesional estilo e-commerce premium, fondo limpio (blanco roto, lino o superficie de madera clara), iluminación de estudio suave con sombras naturales, composición centrada con espacio negativo, paleta de colores armónica, foco nítido. Estilo Apple / Aesop / Muji. Formato cuadrado 1:1. Sin texto, sin logos, sin marcas de agua";
  }

  return `${style}.\n\nSujeto principal: ${subject}.\n\nContexto del producto: ${appDescription.slice(0, 200)}.\n\nLa imagen debe verse 100% real y profesional, como una foto tomada por un fotógrafo humano para una marca de gama alta. Evita el aspecto plástico o sobre-renderizado de IA.`;
}

async function generateOne(
  prompt: string,
): Promise<{ b64_json: string; mimeType: string } | null> {
  try {
    const response = await imageClient.models.generateContent({
      model: "gemini-3-pro-image-preview",
      contents: [{ role: "user", parts: [{ text: prompt }] }],
      config: {
        responseModalities: [Modality.TEXT, Modality.IMAGE],
      },
    });
    const candidate = response.candidates?.[0];
    const imagePart = candidate?.content?.parts?.find(
      (part: { inlineData?: { data?: string; mimeType?: string } }) => part.inlineData,
    );
    if (!imagePart?.inlineData?.data) return null;
    return {
      b64_json: imagePart.inlineData.data,
      mimeType: imagePart.inlineData.mimeType || "image/png",
    };
  } catch (err) {
    logger.warn({ err }, "Nano Banana Pro image generation failed");
    return null;
  }
}

/** Run an async map with bounded concurrency. Errors per item are returned as null. */
async function pMapLimit<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R | null>,
): Promise<(R | null)[]> {
  const results: (R | null)[] = new Array(items.length).fill(null);
  let cursor = 0;
  async function worker() {
    while (cursor < items.length) {
      const idx = cursor++;
      results[idx] = await fn(items[idx]);
    }
  }
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, () => worker()),
  );
  return results;
}

export interface GenerateAppImagesResult {
  /** How many placeholders we found in the bundle (capped at MAX_IMAGES). */
  found: number;
  /** How many real images we successfully generated and stored. */
  generated: number;
  /** Whether the bundle text on the row was rewritten. */
  bundleUpdated: boolean;
}

/**
 * Generate real images for the given app and rewrite its frontend bundle.
 * Idempotent-ish: re-running will pick up any remaining placeholders that
 * weren't yet replaced (the previous successes are already permanent URLs and
 * therefore won't match the placeholder regex anymore).
 */
export async function generateAppImages(
  appId: number,
): Promise<GenerateAppImagesResult> {
  const [row] = await db
    .select()
    .from(generatedApps)
    .where(eq(generatedApps.id, appId))
    .limit(1);
  if (!row) {
    throw new Error("App not found");
  }
  const placeholders = findPlaceholders(row.frontendCode);
  if (placeholders.length === 0) {
    return { found: 0, generated: 0, bundleUpdated: false };
  }

  const generated = await pMapLimit(placeholders, CONCURRENCY, async (p) => {
    const prompt = buildPrompt(p.altText, row.title, row.description);
    const out = await generateOne(prompt);
    if (!out) return null;
    return { placeholder: p, ...out };
  });

  let bundle = row.frontendCode;
  let successCount = 0;
  for (const item of generated) {
    if (!item) continue;
    const [inserted] = await db
      .insert(appImages)
      .values({
        appId,
        mimeType: item.mimeType,
        data: item.b64_json,
        altText: item.placeholder.altText,
        originalUrl: item.placeholder.url,
      })
      .returning({ id: appImages.id });
    const newUrl = `${appBaseUrl()}/api/apps/${appId}/images/${inserted.id}`;
    // Replace ALL occurrences of the placeholder URL — same image often shows
    // up multiple times across the bundle (different components reference it).
    const escaped = item.placeholder.url.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    bundle = bundle.replace(new RegExp(escaped, "g"), newUrl);
    successCount++;
  }

  const bundleUpdated = bundle !== row.frontendCode;
  if (bundleUpdated) {
    await db
      .update(generatedApps)
      .set({ frontendCode: bundle })
      .where(eq(generatedApps.id, appId));
  }

  return {
    found: placeholders.length,
    generated: successCount,
    bundleUpdated,
  };
}
