import { GoogleGenAI, Modality } from "@google/genai";
import { AppImage, GeneratedApp } from "@workspace/db/schema";
import { logger } from "./logger";

/* ============================================================================
 * Maris AI Image Agent — Nano Banana Pro
 *
 * After the Coder finishes a bundle (or on demand from the UI), this scans
 * for placeholder image URLs (Unsplash / picsum / source.unsplash) and
 * replaces them with real images generated by Gemini 3 Pro Image
 * (`gemini-3-pro-image-preview`, a.k.a. Nano Banana Pro).
 *
 * Cost & latency are real concerns:
 *   - Pro images are slow (~10-15s each)
 *   - Capped at MAX_IMAGES per call
 *   - Run with bounded parallelism (CONCURRENCY)
 *   - Failures of individual images are swallowed — we still patch the URLs
 *     that succeeded and leave the rest as placeholders.
 *
 * Storage: rows in `app_images` keyed by app, served as binary from
 * `/api/apps/:appId/images/:imageId` (public, immutable). We replace the
 * placeholder URL in the bundle with that path so it works in both Sandpack
 * preview AND the public `/p/:slug` deploy.
 * ========================================================================== */

const MAX_IMAGES = 20;
const CONCURRENCY = 4;

/**
 * Build the public absolute base URL of the API server. We need ABSOLUTE URLs
 * for the generated image paths because the Sandpack live preview executes
 * the bundle inside an iframe served from a Sandpack-controlled domain
 * (`*.csb.app`), so a relative `/api/apps/3/images/1` would resolve against
 * the Sandpack origin and 404. The same absolute URL also works fine in the
 * public `/p/<slug>` deploy (same origin).
 */
function appBaseUrl(): string {
  const host = (process.env.MARIS_AI_DOMAINS ?? process.env.MARIS_AI_PUBLIC_DOMAINS ?? "").split(",")[0].trim();
  return host ? `https://${host}` : "";
}

// Use the dedicated client so we can pass the Pro model explicitly. The
// shared `ai` client at @workspace/integrations-gemini-ai uses the same env
// vars; we re-instantiate here only because the helper exported from the lib
// pins the flash image model and we want to opt into Pro per the user's
// request ("nano banana pro el nuevo actual").
const imageClient = new GoogleGenAI({
  apiKey: process.env.AI_INTEGRATIONS_GEMINI_API_KEY || process.env.GOOGLE_GENAI_API_KEY || process.env.GEMINI_API_KEY,
  httpOptions: {
    apiVersion: "",
    baseUrl: process.env.AI_INTEGRATIONS_GEMINI_BASE_URL,
  },
});

const PLACEHOLDER_URL_REGEX =
  /https?:\/\/(?:images\.unsplash\.com|source\.unsplash\.com|picsum\.photos)\/[^\s"'`)<>]+/g;

interface FoundPlaceholder {
  url: string;
  altText: string;
}

/**
 * Find unique placeholder URLs in a bundle and grab a small bit of context
 * (alt text or nearby JSX text) for prompting. Order is preserved so the
 * "first 4" the model sees match the order they appear in the source.
 */
export function findPlaceholders(bundle: string): FoundPlaceholder[] {
  const found = new Map<string, FoundPlaceholder>();
  const re = new RegExp(PLACEHOLDER_URL_REGEX.source, "g");
  let m: RegExpExecArray | null;
  while ((m = re.exec(bundle)) !== null) {
    const url = m[0];
    if (found.has(url)) continue;
    // Strip trailing punctuation that can't legally be part of a URL inside JSX.
    const cleanUrl = url.replace(/[.,;:!?]+$/g, "");
    if (found.has(cleanUrl)) continue;
    const start = Math.max(0, m.index - 200);
    const end = Math.min(bundle.length, m.index + cleanUrl.length + 80);
    const window_ = bundle.slice(start, end);
    let altText = "";
    const altMatch = /alt\s*=\s*["'`]([^"'`]{2,160})["'`]/.exec(window_);
    if (altMatch) {
      altText = altMatch[1];
    } else {
      // Fall back to the nearest JSX text node before the URL.
      const before = bundle.slice(start, m.index);
      const textMatch = /[>}]\s*([A-Za-zÀ-ÿ0-9 ,.\-]{4,120})\s*[<{]/g;
      let last: RegExpExecArray | null = null;
      let tm: RegExpExecArray | null;
      while ((tm = textMatch.exec(before)) !== null) last = tm;
      if (last) altText = last[1].trim();
    }
    found.set(cleanUrl, { url: cleanUrl, altText: altText.slice(0, 200) });
    if (found.size >= MAX_IMAGES) break;
  }
  return Array.from(found.values());
}

// Sector detection for contextual image generation
function detectSectorFromApp(title: string, description: string): string {
  const text = (title + " " + description).toLowerCase();
  if (/restaur|comida|food|cafe|bar|cocina|gastro|delivery/.test(text)) return "food";
  if (/salud|clinic|medic|hospital|doctor|dental|psic/.test(text)) return "health";
  if (/fintech|banco|pago|crypto|inversion|credito|finanz/.test(text)) return "finance";
  if (/tienda|shop|venta|producto|compra|ecommerce/.test(text)) return "ecommerce";
  if (/viaje|travel|hotel|vuelo|turismo|reserva/.test(text)) return "travel";
  if (/fitness|gym|deporte|entrenamiento|ejercicio/.test(text)) return "fitness";
  if (/educacion|curso|aprend|academia|tutor|formacion/.test(text)) return "education";
  if (/inmobili|propiedad|piso|casa|alquiler|real estate/.test(text)) return "realestate";
  if (/tech|saas|software|app|startup|digital|plataforma/.test(text)) return "tech";
  return "generic";
}

const SECTOR_STYLE_GUIDES: Record<string, string> = {
  food: "Fotografía gastronómica profesional, iluminación natural cálida, colores ricos y apetecibles, fondos de madera o mármol, profundidad de campo selectiva, estilo Ottolenghi/Kinfolk. Sin texto ni logos.",
  health: "Fotografía médica limpia y profesional, luz natural suave, colores fríos y tranquilizadores (azul, verde menta, blanco), fondos neutros, personas reales con expresiones amables y naturales. Sin texto ni logos.",
  finance: "Fotografía corporativa premium, luz dura y direccional tipo estudio, paleta azul marino y dorado, composición geométrica, fondos oscuros elegantes o blancos limpios. Estilo Bloomberg / McKinsey. Sin texto ni logos.",
  ecommerce: "Fotografía de producto e-commerce premium, fondo blanco limpio o superficie neutra, iluminación de estudio, sombras naturales suaves, composición centrada, foco nítido. Estilo Apple Store / Amazon Premium. Sin texto ni logos.",
  travel: "Fotografía de viajes cinematográfica, paisajes espectaculares con luz dorada de amanecer/atardecer, composición con regla de tercios, colores vibrantes y saturados, sensación de aventura y libertad. Sin texto ni logos.",
  fitness: "Fotografía de fitness dinámica, luz de estudio dramática con fondos oscuros, cuerpos en movimiento, paleta de colores energética (naranja, negro, blanco), composición que transmite fuerza y determinación. Sin texto ni logos.",
  education: "Fotografía educativa luminosa y motivadora, espacios de aprendizaje modernos, luz natural, colores cálidos y amigables, personas concentradas y satisfechas, composición abierta y accesible. Sin texto ni logos.",
  realestate: "Fotografía inmobiliaria de arquitectura premium, gran angular, HDR equilibrado, luz natural maximizada, espacios amplios y luminosos, composición simétrica, colores neutros y elegantes. Sin texto ni logos.",
  tech: "Fotografía tech editorial, fondos oscuros con destellos de luz, dispositivos y pantallas con UI limpia, iluminación LED azulada o violeta, composición futurista, paleta fría y sofisticada. Estilo The Verge / Wired. Sin texto ni logos.",
  generic: "Fotografía profesional premium, iluminación de estudio perfecta, composición equilibrada, colores armónicos, fondo neutro, estilo editorial de gama alta. Sin texto, sin logos, sin marcas de agua.",
};

function buildPrompt(altText: string, appTitle: string, appDescription: string): string {
  const subject = altText && altText.length > 3
    ? altText
    : `imagen ilustrativa para "${appTitle}"`;

  const altLower = altText.toLowerCase();
  const sector = detectSectorFromApp(appTitle, appDescription);

  // Tipo de imagen por contexto del alt text
  const isAvatar = /avatar|usuari|perfil|persona|cara|cliente|vendedor|comprador|review|testimoni|equipo|team/.test(altLower);
  const isHero = /hero|banner|portada|fondo|cover|cabecera|principal|main/.test(altLower);
  const isIcon = /icono|icon|logo|symbol|badge/.test(altLower);
  const isMap = /mapa|map|location|ubicacion|direccion/.test(altLower);
  const isDashboard = /dashboard|panel|grafico|chart|estadistic/.test(altLower);

  let baseStyle: string;
  if (isAvatar) {
    baseStyle = "Retrato fotografico profesional de una persona real. Angulo frontal o 3/4, fondo desenfocado neutro, iluminacion natural suave tipo ventana, expresion amable y natural, encuadre desde los hombros hacia arriba, foco nitido en los ojos. Estilo editorial moderno tipo LinkedIn Premium o Apple. Formato cuadrado 1:1.";
  } else if (isHero) {
    baseStyle = `Imagen hero cinematografica de gran formato. ${SECTOR_STYLE_GUIDES[sector]} Profundidad de campo amplia, iluminacion con direccion clara, composicion que respira con espacio negativo, paleta de colores limitada y sofisticada.`;
  } else if (isIcon) {
    baseStyle = "Icono digital minimalista 3D, fondo degradado suave, sombra larga, colores vibrantes y modernos, estilo Dribbble Premium. Formato cuadrado 1:1.";
  } else if (isDashboard) {
    baseStyle = "Mockup de interfaz digital sobre pantalla de MacBook o monitor moderno, fondo oscuro elegante, destellos de luz ambiente, UI limpia y moderna visible en pantalla. Estilo media kit de startup tech. Formato cuadrado 1:1.";
  } else {
    baseStyle = SECTOR_STYLE_GUIDES[sector] || SECTOR_STYLE_GUIDES.generic;
  }

  // Prompt final enriquecido con contexto de producto
  return `${baseStyle}

Sujeto principal: ${subject}.

Contexto del producto: ${appDescription.slice(0, 150)}.

La imagen debe verse 100% real y profesional, indistinguible de una foto tomada por un fotografo humano para una marca de gama alta. Fotorrealismo maximo. Evita el aspecto plastico, sobre-saturado o irreal tipico de IA generativa. Formato cuadrado 1:1 perfecto.`;
}

// Modelos de imagen en orden de preferencia (fallback automatico)
// Sector-aware image generation prompts
function buildSectorImageHint(altText: string, appTitle: string): string {
  const lower = (altText + " " + appTitle).toLowerCase();
  if (/restaur|comida|cafe|bar|menu|delivery/.test(lower)) return "food photography, warm lighting, appetizing, professional restaurant";
  if (/salud|medic|clinic|doctor|hospital/.test(lower)) return "healthcare, clean, professional, trustworthy, medical setting";
  if (/inmobili|casa|piso|apartament|propiedad/.test(lower)) return "real estate photography, bright interior, modern home, professional";
  if (/deport|gym|fitness|entrena|futbol/.test(lower)) return "sports photography, dynamic, energetic, action shot";
  if (/viaje|hotel|turismo|playa|vacacion/.test(lower)) return "travel photography, stunning landscape, professional tourism";
  if (/moda|ropa|fashion|tienda|boutique/.test(lower)) return "fashion photography, editorial, clean background, professional";
  if (/negocio|empresa|corporativ|profesional/.test(lower)) return "business photography, professional, corporate, clean office";
  return "professional photography, high quality, modern, clean background";
}

const IMAGE_MODELS = [
  "gemini-3-pro-image-preview",
  "gemini-2.0-flash-preview-image-generation",
  "imagen-3.0-generate-002",
];

async function generateOne(
  prompt: string,
): Promise<{ b64_json: string; mimeType: string } | null> {
  // Intentar con cada modelo hasta que uno funcione
  for (const model of IMAGE_MODELS) {
    for (let attempt = 1; attempt <= 2; attempt++) {
      try {
        const response = await imageClient.models.generateContent({
          model,
          contents: [{ role: "user", parts: [{ text: prompt }] }],
          config: {
            responseModalities: [Modality.TEXT, Modality.IMAGE],
          },
        });
        const candidate = response.candidates?.[0];
        const imagePart = candidate?.content?.parts?.find(
          (part: { inlineData?: { data?: string; mimeType?: string } }) => part.inlineData,
        );
        if (imagePart?.inlineData?.data) {
          logger.info({ model, attempt }, "Image Agent: imagen generada OK");
          return {
            b64_json: imagePart.inlineData.data,
            mimeType: imagePart.inlineData.mimeType || "image/png",
          };
        }
        // Si no hay imagen en la respuesta, intentar con prompt simplificado
        if (attempt === 1) {
          logger.warn({ model }, "Image Agent: sin imagen en respuesta, reintentando con prompt reducido");
        }
      } catch (err: any) {
        const msg = err?.message || "";
        // Si el modelo no existe o hay error de cuota, pasar al siguiente
        if (msg.includes("not found") || msg.includes("quota") || msg.includes("billing")) {
          logger.warn({ model, err: msg }, "Image Agent: modelo no disponible, probando siguiente");
          break; // Saltar al siguiente modelo
        }
        if (attempt < 2) await new Promise(r => setTimeout(r, 1500));
        logger.warn({ model, attempt, err: msg }, "Image Agent: intento fallido");
      }
    }
  }
  logger.warn("Image Agent: todos los modelos fallaron para esta imagen");
  return null;
}

/** Run an async map with bounded concurrency. Errors per item are returned as null. */
async function pMapLimit<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R | null>,
): Promise<(R | null)[]> {
  const results: (R | null)[] = new Array(items.length).fill(null);
  let cursor = 0;
  async function worker() {
    while (cursor < items.length) {
      const idx = cursor++;
      results[idx] = await fn(items[idx]);
    }
  }
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, () => worker()),
  );
  return results;
}

export interface GenerateAppImagesResult {
  /** How many placeholders we found in the bundle (capped at MAX_IMAGES). */
  found: number;
  /** How many real images we successfully generated and stored. */
  generated: number;
  /** Whether the bundle text on the row was rewritten. */
  bundleUpdated: boolean;
}

/**
 * IMAGE AGENT — Agente #8 del equipo Maris AI
 * IDENTIDAD: Genera imagenes reales para reemplazar placeholders de Unsplash/picsum.
 * CHAIN OF THOUGHT: 1) Analiza el alt text del placeholder. 2) Detecta el sector de la app.
 * 3) Construye un prompt fotografico profesional y especifico. 4) Genera y reemplaza.
 * ANTI-DESVIO: Genera SOLO imagenes relacionadas con el contenido del proyecto.
 * Si el alt dice "foto de perfil de usuario", genera un retrato — no un paisaje.
 */

/**
 * Generate real images for the given app and rewrite its frontend bundle.
 * Idempotent-ish: re-running will pick up any remaining placeholders that
 * weren't yet replaced (the previous successes are already permanent URLs and
 * therefore won't match the placeholder regex anymore).
 */
export async function generateAppImages(
  appId: number,
): Promise<GenerateAppImagesResult> {
  const row = await GeneratedApp.findById(appId).lean();
  if (!row) {
    throw new Error("App not found");
  }
  const placeholders = findPlaceholders(row.frontendCode);
  if (placeholders.length === 0) {
    return { found: 0, generated: 0, bundleUpdated: false };
  }

  const generated = await pMapLimit(placeholders, CONCURRENCY, async (p) => {
    const prompt = buildPrompt(p.altText, row.title, row.description);
    const out = await generateOne(prompt);
    if (!out) return null;
    return { placeholder: p, ...out };
  });

  let bundle = row.frontendCode;
  let successCount = 0;
  for (const item of generated) {
    if (!item) continue;
    const inserted = await AppImage.create({
      appId: String(appId),
      mimeType: item.mimeType,
      data: item.b64_json,
      altText: item.placeholder.altText,
      originalUrl: item.placeholder.url,
    });
    const newUrl = `${appBaseUrl()}/api/apps/${appId}/images/${inserted._id}`;
    // Replace ALL occurrences of the placeholder URL — same image often shows
    // up multiple times across the bundle (different components reference it).
    const escaped = item.placeholder.url.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    bundle = bundle.replace(new RegExp(escaped, "g"), newUrl);
    successCount++;
  }

  const bundleUpdated = bundle !== row.frontendCode;
  if (bundleUpdated) {
    await GeneratedApp.updateOne({ _id: appId }, { frontendCode: bundle });
  }

  return {
    found: placeholders.length,
    generated: successCount,
    bundleUpdated,
  };
}
